# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed N, find the sum of the even-valued terms.

def even_fibo(n):
    num1, num2 = 0, 1
    fibo_arr = []
    while num2 < n:
        num1, num2 = num2, num1+num2
        fibo_arr.append(num1)
    return [n for n in fibo_arr[:] if n % 2 == 0]

t = int(input().strip())

for _ in range(t):
    n = int(input().strip())
    print(sum(even_fibo(n)))